name: Context examples
on: [push]

jobs: 
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1"
        env: 
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
        run: |
          echo "Hello $MY_ACTION"
          echo "Hello $MY_ACTOR"