name: Manual Trigger with Params

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        type: string
        required: true
      greeting:
        description: 'Type of greeting'
        type: string
        required: true
      data:
        description: 'Base64 encoded content of a file'
        type: string
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: decode file content
        run: |
          echo "${{inputs.data}}" | base64 --decode > ./decoded_file.txt
      - name: display greeting
        run: |
          echo "${{inputs.greeting}} ${{inputs.name}}!"
      - name: display file content
        run: |
          echo "Content of the file"
          cat ./decoded_file.txt

