name: sheduled hello world
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  sheduled-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"