name: Webhook event example

on:
  repositoty_dispatch:
    types:
      - webhook

jobs:
  respond-to-repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: log event name
        run: echo "Event of type $GITHUB_EVENT_NAME"

